// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tutorial

import (
	"database/sql"
	"time"
)

type Company struct {
	ID           interface{}
	Name         string
	Country      string
	CreationDate sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Group struct {
	ID        interface{}
	Name      string
	Type      interface{}
	DebutDate sql.NullTime
	CompanyID sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GroupMember struct {
	ID        interface{}
	GroupID   sql.NullInt64
	IdolID    sql.NullInt64
	SinceDate sql.NullTime
	UntilDate sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Idol struct {
	ID         interface{}
	StageName  string
	Name       string
	Gender     interface{}
	IdolInfoID sql.NullInt64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type IdolInfo struct {
	ID        interface{}
	Birthdate sql.NullTime
	HeightCm  sql.NullFloat64
	WeightKg  sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}
