// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: idols.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdol = `-- name: CreateIdol :one
INSERT INTO idols (
    stage_name,
    name,
    gender
) VALUES (
  $1, $2, $3
)
RETURNING id, stage_name, name, gender, created_at, updated_at
`

type CreateIdolParams struct {
	StageName string
	Name      pgtype.Text
	Gender    string
}

func (q *Queries) CreateIdol(ctx context.Context, arg CreateIdolParams) (Idol, error) {
	row := q.db.QueryRow(ctx, createIdol, arg.StageName, arg.Name, arg.Gender)
	var i Idol
	err := row.Scan(
		&i.ID,
		&i.StageName,
		&i.Name,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdolByName = `-- name: GetIdolByName :one
SELECT id, stage_name, name, gender, created_at, updated_at FROM idols
WHERE name = $1 or stage_name = $1
LIMIT 1
`

func (q *Queries) GetIdolByName(ctx context.Context, name pgtype.Text) (Idol, error) {
	row := q.db.QueryRow(ctx, getIdolByName, name)
	var i Idol
	err := row.Scan(
		&i.ID,
		&i.StageName,
		&i.Name,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdols = `-- name: ListIdols :many
SELECT id, stage_name, name, gender, created_at, updated_at FROM idols
`

func (q *Queries) ListIdols(ctx context.Context) ([]Idol, error) {
	rows, err := q.db.Query(ctx, listIdols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idol
	for rows.Next() {
		var i Idol
		if err := rows.Scan(
			&i.ID,
			&i.StageName,
			&i.Name,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
